### PR TITLE
Feature/hot reload

### PR DESCRIPTION
**Pull request by mr-mig**
Added hot **reloading for components** (both reactjs and styles are supported).
No need to refresh the page.

**Note:** you need to add this entry to your `conf/application.conf`:
```
yetu {
  frontendBundlePath="//local.yetudev.com:8899/assets/"
}
```

To start server with hotreload run:
```
npm start
```
and then in a separate terminal window:
```
sbt run
```

### CODE REVIEW

**Comment by larsblumberg** [comment]
Can I combine both `npm start` and `sbt run` into a single command to be run in a single terminal window?

**Comment by larsblumberg** [comment]
LGTM

**Comment by mr-mig** [comment]
I will close this one and add the run scripts.

**Comment by DaQuirm** [comment]
LGTM too

**Pull request closed without merging**
