### PR TITLE
Fix/cleanup

### PR DESCRIPTION
**Pull request by mr-mig**

### CODE REVIEW

**Comment by larsblumberg** [comment]
Fine

**Comment by mr-mig** [comment]
@dev-tim @DaQuirm

**Comment by dev-tim** [comment]
:+1:

**Comment by dev-tim** [comment]
Do indentation settings will be caught by IDEA automatically?

**Comment by mr-mig** [comment]
@dev-tim no, we need to think about sharing IDEAs settings in addition to `.editorconfig`

**Pull request merged**
