### PR TITLE
Enable Oauth2 Flow for controlcenter and secure entry point

### PR DESCRIPTION
**Pull request by enginyoyen**
Enable Oauth2 Flow for controlcenter and secure entry point.
PS; after merging this pull request you need to add in your repository application.conf which will hold the oauth2 credentials for development environment.

### CODE REVIEW

**Comment by mr-mig** [comment]
LGTM :+1:

**Comment by jschaul** [comment]
There is no test. Please add one; the BaseRoute for a faked authentication is already set up.

**Comment by jschaul** [comment]
Thanks. LGTM.

**Comment by dev-tim** [comment]
:+1:

**Pull request merged**
