### PR TITLE
Implement device renaming

### PR DESCRIPTION
**Pull request by DaQuirm**

### CODE REVIEW

**Comment by larsblumberg** [comment]
LGTM :+1:

**Comment by DaQuirm** [comment]
Yay, just in time! Are we having a walkthrough tomorrow? It wasn't cancelled, right? :smile_cat:

**Comment by ghophp** [comment]
:-1:

**Comment by ElliDy** [comment]
Hehe...very funny. Btw, how are you three?

**Comment by DaQuirm** [comment]
And here I was, hoping I'd be the one behind PR #100.
But it never happened and never will :crying_cat_face: 

Hi Elisa! We're good, I guess?.. Feeling nostalgic though :cat: 
How are you?

**Comment by ElliDy** [comment]
I´m fine. Working now at http://www.queo-group.com/ ;) Feeling good here in Dresden... but still I miss Berlin, the people there and the culture. And of course also sometimes thinking back on the good old times at yetu... what do you think about having some come together near christmas? I would like to know, how you all are doing :)

**Pull request merged**
